### ISSUE TITLE
Error 'Unknown model (DVT_T2t_vit_12)'

### ISSUE THREAD

**Issue by xiyiyia** [blackfeather-wang/Dynamic-Vision-Transformer#5]
Hi!

I try to evaluate the DVT_T2t_vit_12, then I run 'python inference.py --data_url ./data/ --batch_size 64 --model DVT_T2t_vit_12 --checkpoint_path .\checkpoint\DVT_T2t_vit_12.pth.tar  --eval_mode 1', I get the error.

"
Traceback (most recent call last):
  File "inference.py", line 226, in <module>
    main()
  File "inference.py", line 57, in main
    model = create_model(
  File "A:\transformer\DViT\Dynamic-Vision-Transformer-main\Dynamic-Vision-Transformer-main\timm\models\factory.py", line 59, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (DVT_T2t_vit_12)
"

And I try to print the _model_entrypoints, which in ..Dynamic-Vision-Transformer-main/timm/models/registry.py to find the model name'DVT_T2t_vit_12'. I don't see that.

env: python:3.8 pytorch:1.8.1 torchvision 0.9.1

**Comment by xiyiyia** [comment]
It works if you put the `model_deit.py` to the `timm/models/`. And you only can use the DVT_Deit_small model. If you want to use others, better to put the `./models/*` to `timm/models/`.
